AWSTemplateFormatVersion: '2010-09-09'
Description: Create a role to authorize the VPC Peering request from a specific account, this is used to create the VPC Peer between different accounts in CloudFormation

Parameters:
  MetaServicesAccountId:
    Type: String
    Default: '1234567890123'
    Description: Number of the requester account

Resources:
  VPCPeeringAuthorizerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref MetaServicesAccountId
                  - ':root'
            Action: sts:AssumeRole
      Policies:
        - PolicyName: VPCAuthorizer
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:AcceptVpcPeeringConnection
                Resource:
                  - "*"
      RoleName: !Join
        - ''
        - - !Ref "AWS::Region"
          - '-VPCPeerAuthorizerRole-'
          - !Ref MetaServicesAccountId

Outputs:
  RoleName:
    Description: Cross Account Role Name
    Value: !Ref VPCPeeringAuthorizerRole
